### ISSUE TITLE
cdn ranges updated needed 

### ISSUE THREAD

**Issue by mrvcoder** [ImAyrix/cut-cdn#11]
hello Amirabbas 
thanks for developing this awesome tool

can you please update the cdn-ranges ?

for example this ip is for cloud flare cdn :
```
 echo  "141.193.213.21" | cut-cdn 
[INF] Create Cut-CDN Providers File
[INF] Create CDN CIDRs File
[INF] Loading All CDN Range
[INF] All CDN Range Loaded
[INF] Input Parsing
[INF] Input Parsed
[INF] Start Checking IPs

[⚡] All IPs Not 
Behind CDN ⤵
141.193.213.21
``` 

[https://check-host.net/ip-info?host=141.193.213.21](https://check-host.net/ip-info?host=141.193.213.21)

**Comment by ImAyrix** [comment]
Hello! 👋

List of CIDRs for the Cloudflare CDN service are available at this link: [Cloudflare IPv4 CIDR](https://www.cloudflare.com/ips-v4).

Cut-cdn matches this list, so whenever you run the following command, the tool automatically updates its IP list using the links provided in the [providers.yaml](https://github.com/ImAyrix/cut-cdn/blob/master/static/providers.yaml) file:

```bash
cut-cdn -update-ranges
```
I also checked the [IP](http://141.193.213.21) that you sent, and it was not one of the CIDRs provided by Cloudflare. 
Thank you for creating an issue and sending your problem. Good luck ❤️
