### ISSUE TITLE
Iranian Providers

### ISSUE THREAD

**Issue by meweez** [ImAyrix/cut-cdn#6]
Hi,
Thank you for your useful tool.
Can you please add other providers like CafeBazaar and Arvan?
Thanks

**Comment by ImAyrix** [comment]
Hi meweez,

Cut-CDN checks the range of Arvan Cloud IPs, but if there is a link or page that lists Cafe Bazaar's CIDRs, I would appreciate it if you could share it with me. 

Thank you.

**Comment by meweez** [comment]
These are anycast IPs for CafeBazaar CDN:
185.166.104.4
185.166.104.3

**Comment by meweez** [comment]
I have updated my previous comment:
This link list all anycast IPs for Sotoon CDN:
http://edge.sotoon.ir/ip-list.json
Thanks a lot!

**Comment by ImAyrix** [comment]
Thanks meweez, 

The range of Cafe Bazaar IPs has been added to Cut-CDN, so all you need to do is update Cut-CDN.
